name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build website
        run: flutter build web --release
      - name: Apply build
        uses: EndBug/add-and-commit@v9
        with:
          message: 'build website'
