name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          flutter build web --release
          cp -r build/web/* docs/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "build website"
          git push
