name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build website
        run: flutter build web --release
      - name: Copy website into docs dir
        run: cp -r build/web/* docs/
      - name: Apply build
        uses: EndBug/add-and-commit@v9
        with:
          message: 'build website'
          author_name: Jonas Fassbender
          author_email: jonas@fc-web.de
