name: Publish
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  Publish:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install build-essential
          npm install -D tailwindcss
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: make release
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
